name: 'JUnit Report Action'
description: 'Report JUnit test results as annotations on Github Pull Request [junit]'
branding:
  icon: 'check-circle'
  color: 'green'
inputs:
  token:
    description: 'Specify the token to use to publish the check.'
    required: true
  github_token:
    description: 'Deprecated syntax to specify github token.'
    required: true
  report_paths:
    description: 'JUnit xml report paths in glob format'
    required: false
    default: '**/junit-reports/TEST-*.xml'
  suite_regex:
    description: 'Regular expression for the named test suites'
    required: false
    default: ''
  check_name:
    description: 'Check name for test reports.'
    required: false
    default: 'JUnit Test Report'
  commit:
    description: 'Commit SHA to update the check status.'
    required: false
  fail_on_failure:
    description: 'Fail the build in case a test failure occurred.'
    required: false
    default: 'false'
  require_tests:
    description: 'Fail if no test are found.'
    required: false
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
